version: 2

aliases:
  - &docker
    - image: cimg/node:24.0

  - &restore_yarn_cache
    restore_cache:
      name: Restore yarn cache
      key: v3-node-{{ arch }}-{{ checksum "yarn.lock" }}-yarn

  - &restore_node_modules
    restore_cache:
      name: Restore node_modules cache
      key: v3-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}-node-modules

jobs:
  build:
    working_directory: ~/neh
    docker: *docker
    steps:
      - checkout
      - *restore_yarn_cache
      - *restore_node_modules
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn --non-interactive
      - save_cache:
          name: Save yarn cache for future installs
          key: v3-node-{{ arch }}-{{ checksum "yarn.lock" }}-yarn
          paths:
            - ~/.cache/yarn
      - save_cache:
          name: Save node_modules cache
          key: v3-node-{{ arch }}-{{ .Branch }}-{{ checksum "yarn.lock" }}-node-modules
          paths:
            - node_modules
      - run:
          name: Build assets
          command: yarn build
      - run:
          name: Typecheck Code
          command: yarn typecheck
      - run:
          name: Run Linters
          command: yarn lint
      - run:
          name: Test code
          environment:
            NODE_ENV: test
          command: |
            set -e
            yarn test
            curl -Os https://uploader.codecov.io/latest/linux/codecov
            chmod +x codecov
            ./codecov -f ./coverage/coverage-final.json
      - store_test_results:
          path: test-reports

  deploy:
    working_directory: ~/neh
    docker: *docker
    steps:
      - checkout
      - *restore_yarn_cache
      - run:
          name: Install dependencies
          command: yarn --frozen-lockfile --cache-folder ~/.cache/yarn --non-interactive
      - run: yarn run publish

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
          context: neh-cf-deploy
