// scripts/build-assets.js
const pug = require('pug');
const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');
const os = require('os');
const crypto = require('crypto');

// 1. Compile Pug template → JS module
const pugSrc = fs.readFileSync(
  path.join(__dirname, '../src/handlers/list/template.pug'),
  'utf-8',
);
const compiledFn = pug.compileClient(pugSrc, {
  name: 'template',
  inlineRuntimeFunctions: true, // self-contained, no pug-runtime dep
});
const jsOut = `// AUTO-GENERATED — do not edit; regenerated by scripts/build-assets.js
${compiledFn}
export { template as default };
`;
fs.writeFileSync(
  path.join(__dirname, '../src/handlers/list/template.generated.js'),
  jsOut,
);

// 2. Run Tailwind CLI → CSS file (unique temp path to avoid concurrent CI races)
const tmpCss = path.join(os.tmpdir(), `tw-generated-${crypto.randomBytes(4).toString('hex')}.css`);
execSync(
  `npx @tailwindcss/cli --input src/resources/tailwind.css --output ${tmpCss} --minify`,
  { stdio: 'inherit' },
);

// 3. Wrap CSS as a TS string module
const css = fs.readFileSync(tmpCss, 'utf-8');
fs.unlinkSync(tmpCss);
const tsOut = `// AUTO-GENERATED — do not edit; regenerated by scripts/build-assets.js
const css = ${JSON.stringify(css)};
export default css;
`;
fs.writeFileSync(
  path.join(__dirname, '../src/resources/generated-css.ts'),
  tsOut,
);

console.log('build-assets: done');
