import css from './resources/generated-css';

function escapeHtml(s: string): string {
  const map: Record<string, string> = {
    '&': '&amp;',
    '<': '&lt;',
    '>': '&gt;',
    '"': '&quot;',
    "'": '&#39;',
  };
  return s.replace(/[&<>"']/g, (c) => map[c]);
}

function renderParagraphs(content: string): string {
  return content
    .split(/\n{2,}/)
    .map((p) => p.trim())
    .filter((p) => p.length > 0)
    .map((p) => `<p class="my-3">${escapeHtml(p).replace(/\n/g, '<br>')}</p>`)
    .join('');
}

function layout(title: string, bodyHtml: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(title)} · neh</title>
<style>${css}</style>
</head>
<body>
<div class="py-10 max-w-3xl mx-auto px-3 sm:px-4">${bodyHtml}</div>
</body>
</html>`;
}

export function renderResultPage(label: string, content: string, sourceUrl: string): Response {
  const body = `
<h1 class="font-black leading-none text-6xl mt-10 mb-8">👇 NEH!</h1>
<p class="text-xs uppercase tracking-wide text-gray-500 my-3">${escapeHtml(label)}</p>
<p class="text-sm text-gray-700 mb-8">Source: <a class="underline" href="${escapeHtml(sourceUrl)}">${escapeHtml(sourceUrl)}</a></p>
<div class="text-gray-700">${renderParagraphs(content)}</div>
<p class="mt-10 text-gray-500 text-sm">Generated by <a href="/" class="underline">neh</a>.</p>
`;
  return new Response(layout(label, body), {
    headers: { 'content-type': 'text/html;charset=UTF-8' },
  });
}

export function renderErrorPage(command: string, message: string, status = 500): Response {
  const body = `
<h1 class="font-black leading-none text-6xl mt-10 mb-8">😬</h1>
<p class="text-xs uppercase tracking-wide text-gray-500 my-3">${escapeHtml(command)}</p>
<p class="text-gray-700 my-3">${escapeHtml(message)}</p>
<p class="mt-10 text-gray-500 text-sm"><a class="underline" href="/">neh</a></p>
`;
  return new Response(layout(command, body), {
    status,
    headers: { 'content-type': 'text/html;charset=UTF-8' },
  });
}
