declare module '*.txt' {
  const contents: string;
  export = contents;
}

declare module '*.xml' {
  const contents: string;
  export = contents;
}

// Pre-compiled pug function (generated by scripts/build-assets.js)
declare module '*/template.generated.js' {
  function template(locals: Record<string, unknown>): string;
  export default template;
}
